CREATE DATABASE IF NOT EXISTS triggers;
USE triggers;


CREATE TABLE BUS(
    BUSNO VARCHAR(10) NOT NULL,
    SOURCE VARCHAR(10),
    DESTINATION VARCHAR(10),
    CAPACITY INT(2),
    PRIMARY KEY(BUSNO)
);

DESC BUS;

INSERT INTO BUS
VALUES('AP123', 'HYD', 'CHENNAI', '40');

SELECT * FROM BUS;

CREATE TABLE BUS_AUDIT1(
    ID INT NOT NULL AUTO_INCREMENT,
    SOURCE VARCHAR(10) NOT NULL,
    CHANGEDON DATETIME DEFAULT NULL,
    ACTION VARCHAR(10) DEFAULT NULL,
    PRIMARY KEY(ID)
);


DESC BUS_AUDIT1;

DELIMITER //



CREATE TRIGGER BEFORE_BUS_UPDATE BEFORE
UPDATE ON BUS FOR EACH ROW BEGIN
INSERT INTO BUS_AUDIT1
SET action = 'update',
    source = OLD.source,
    changedon = NOW();
END //


UPDATE BUS
SET SOURCE = 'KERALA'
WHERE BUSNO = 'AP123' //

SELECT * FROM BUS//

SELECT * FROM BUS_AUDIT1//

CREATE TRIGGER BEFORE_BUS_INSERT BEFORE
INSERT ON BUS FOR EACH ROW BEGIN
INSERT INTO BUS_AUDIT1
SET action = 'Insert',
    source = NEW.source,
    changedon = NOW();
END //


INSERT INTO BUS
VALUES('AP789', 'VIZAG', 'HYDERABAD', 30) // 

SELECT * FROM BUS;
SELECT * FROM BUS_AUDIT1//

CREATE TRIGGER BEFORE_BUS_DELETE 
BEFORE DELETE ON BUS 
FOR EACH ROW BEGIN
DELETE FROM BUS_AUDIT1
SET action = 'Delete',
    source = OLD.source,
    changedon = NOW();
END //


DELETE FROM BUS
WHERE SOURCE = 'HYDERABAD' //

SELECT * FROM BUS;
SELECT * FROM BUS_AUDIT1//

DELIMITER ;